### ISSUE TITLE
投个稿

### ISSUE THREAD

**Issue by rpdreamer** [ForkFG/OI-Nazo#2]
[UVA12376 As Long as I Learn, I Live](https://www.luogu.org/problem/UVA12376)

提示：
1. 题目界面：学到老，活到老
2. console输入学到老活到老输出As Long as I Learn, I Live

答案是UVA12376

希望成为出题组QAQ

**Comment by qwoiqwq** [comment]
我觉得这个问题毫无意义。而且选手也猜不到。

**Comment by rpdreamer** [comment]
> 我觉得这个问题毫无意义。而且选手也猜不到。

emmmm

**Comment by ForkFG** [comment]
猜不到？

**Comment by ForkFG** [comment]
我觉得这题太简单  
但是可以考虑结合即将推出的 php 解题

**Comment by qwoiqwq** [comment]
我觉得让人去猜一个题目名是很无聊的事情。同时就算猜到了，他也没理由就要输入uva12376。

**Comment by ForkFG** [comment]
这个没问题，剧情配合暗示一下就行

**Comment by ForkFG** [comment]
进群说呗？774225409

**Comment by ForkFG** [comment]
PS: 出题组没问题的，欢迎！

**Comment by rpdreamer** [comment]
> PS: 出题组没问题的，欢迎！

再来一个：

![](https://raw.githubusercontent.com/rpdreamer/images/master/icelava.jpg)

下载文件后改后缀为rar
